"""add knowledge source metadata

Revision ID: d28512c1716d
Revises: af17296f0214
Create Date: 2026-09-17 16:45:20.243559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28512c1716d'
down_revision: Union[str, Sequence[str], None] = 'af17296f0214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_type', sa.String(length=4), server_default=sa.text("'file'"), nullable=False))
    op.create_check_constraint("ck_documents_source_type", "documents", "source_type IN ('file', 'url')")
    op.add_column('documents', sa.Column('source_url', sa.String(length=2048), nullable=True))
    op.add_column('documents', sa.Column('category', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('audience', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('effective_from', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('effective_to', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_documents_source_url', 'documents', ['source_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_source_url', 'documents', type_='unique')
    op.drop_constraint('ck_documents_source_type', 'documents', type_='check')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'effective_to')
    op.drop_column('documents', 'effective_from')
    op.drop_column('documents', 'last_checked_at')
    op.drop_column('documents', 'published_at')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'audience')
    op.drop_column('documents', 'category')
    op.drop_column('documents', 'source_url')
    op.drop_column('documents', 'source_type')
    # ### end Alembic commands ###
